apiVersion: apps/v1
kind: Deployment
metadata:
  name: bevco-api-gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: bevco-api
          image: 767397657417.dkr.ecr.us-east-1.amazonaws.com/api-gateway:latest
          env:
          - name: INVENTORY_URL
            value: 'http://bevco-inventory-srv:3000'
          - name: RESTOCK_URL
            value: 'http://bevco-restock-srv:3000'
---
apiVersion: v1
kind: Service
metadata:
  name: bevco-api-srv
spec:
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer