---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: inventory-depl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-depl
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50