apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bevco-inventory
  template:
    metadata:
      labels:
        app: bevco-inventory
    spec:
      containers:
        - name: bevco-inventory
          image: 767397657417.dkr.ecr.us-east-1.amazonaws.com/inventory:latest
          readinessProbe:
            httpGet:
              path: /api/inventory/heath
              port: 3000
          livenessProbe:
            httpGet:
              path: /api/inventory/heath
              port: 3000
          env:
          - name: DATABASE
            value: 'mongodb://inventory-mongo-srv:27017/inventory'
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "75m"
---
apiVersion: v1
kind: Service
metadata:
  name: bevco-inventory-srv
spec:
  selector:
    app: bevco-inventory
  ports:
    - name: bevco-inventory
      protocol: TCP
      port: 3000
      targetPort: 3000