apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-mongo-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-mongo
  template:
    metadata:
      labels:
        app: inventory-mongo
    spec:
      containers:
        - name: inventory-mongo
          image: mongo
          volumeMounts:
            - name: inventory-mongo-storage
              mountPath: /data/db
      volumes:
        - name: inventory-mongo-storage
          persistentVolumeClaim:
            claimName: inventory-mongo-ebs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-mongo-srv
spec:
  selector:
    app: inventory-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017