apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-srv
spec:
  persistence:
    storageClassName: ebs-sc
    storage: "10Gi"
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 200m
      memory: 250Mi